#!/bin/bash
myFile="/home/zhuoranh/Documents/MIT/simplemc/results"
a=100000
if [ -f "$myFile" ]; then
  echo "Deleted Old File."
  rm "$myFile"
fi
echo "Running. Please Wait."
#date >> "$myFile"
#./MC 1 1.00 $a >> "$myFile"
#date >> "$myFile"
#./MC 1 1.1 $a >> "$myFile"
#date >> "$myFile"
#./MC 1 1.2 $a >> "$myFile"
date >> "$myFile"
./MC 1 1.3 $a >> "$myFile"
#date >> "$myFile"
#./MC 1 1.4 $a >> "$myFile"
echo -e "########Geo run done.####### \n" >> "$myFile"
#date >> "$myFile"
#./MC 1.00 1 $a >> "$myFile"
#date >> "$myFile"
#./MC 1.1 1 $a >> "$myFile"
#date >> "$myFile"
#./MC 1.2 1 $a >> "$myFile"
date >> "$myFile"
./MC 1.3 1 $a >> "$myFile"
#date >> "$myFile"
#./MC 1.4 1 $a >> "$myFile"
echo -e "########VD run done.#######\n" >> "$myFile"
